/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as CvRouteImport } from './routes/cv'
import { Route as OngoingRouteImport } from './routes/ongoing'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ServiceRouteImport } from './routes/service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingRoute = OngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/cv': typeof CvRoute
  '/ongoing': typeof OngoingRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/service': typeof ServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/cv': typeof CvRoute
  '/ongoing': typeof OngoingRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/service': typeof ServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/cv': typeof CvRoute
  '/ongoing': typeof OngoingRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/service': typeof ServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/cv'
    | '/ongoing'
    | '/publications'
    | '/research'
    | '/service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/cv'
    | '/ongoing'
    | '/publications'
    | '/research'
    | '/service'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/cv'
    | '/ongoing'
    | '/publications'
    | '/research'
    | '/service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  CvRoute: typeof CvRoute
  OngoingRoute: typeof OngoingRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  ServiceRoute: typeof ServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing': {
      id: '/ongoing'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof OngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  CvRoute: CvRoute,
  OngoingRoute: OngoingRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  ServiceRoute: ServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
